[package]
name = "risc0-builder"
version = "0.1.0"
edition = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raiko-pipeline = { path = "../../../pipeline", features = ["risc0"]}

[features]
test = []
