//! SP1 Guest ELF binaries
//!
//! This module contains the ELF binaries for the SP1 guest programs.
//! These are generated by the build-guest.sh script.

/// Batch proof ELF binary
pub const SP1_BATCH_ELF: &[u8] = include_bytes!("elf/sp1_batch.elf");

/// Shasta aggregation ELF binary
pub const SP1_SHASTA_AGGREGATION_ELF: &[u8] = include_bytes!("elf/sp1_shasta_aggregation.elf");
