# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "raiko-setup"
version = "0.1.0"
edition = "2021"

[dependencies]
# sp1-driver = { path = "../provers/sp1/driver", optional = true }
# risc0-driver = { path = "../provers/risc0/driver", optional = true }
sgx-prover = { path = "../prover", optional = true }

# raiko
raiko-lib = { workspace = true, features = ["c-kzg"] }

# alloy
alloy-rlp = { workspace = true }
alloy-rlp-derive = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-provider = { workspace = true }
alloy-transport-http = { workspace = true }
alloy-consensus = { workspace = true }
alloy-network = { workspace = true }
alloy-rpc-client = { workspace = true }

# misc
anyhow = { workspace = true }
bincode = { workspace = true }
bytemuck = { workspace = true }
clap = { workspace = true }
structopt = { workspace = true }
flate2 = { workspace = true }
revm = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
hyper = { workspace = true }
env_logger = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
tower = { workspace = true }
lru_time_cache = { workspace = true }
prometheus = { workspace = true }
lazy_static = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
reqwest_alloy = { workspace = true }
sha2 = { workspace = true }
proptest = { workspace = true }
rlp = { workspace = true }
url = { workspace = true }
cfg-if = { workspace = true }
cap = { workspace = true }
dirs = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
rstest = { workspace = true }
ethers-core = { workspace = true }

# [build-dependencies]
# sp1-helper = { workspace = true }

[features]
default = ["sgx"]
# sp1 = [
#   "dep:sp1-driver",
#   "sp1-driver/enable",
# ]
# risc0 = [
#   "dep:risc0-driver",
#   "risc0-driver/enable",
# ]
sgx = ["dep:sgx-prover", "sgx-prover/enable"]
