# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[package]
name = "raiko-setup"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "raiko-setup"
required-features = ["sgx"]

[dependencies]
sgx-prover = { path = "../prover", features = ["enable"] }

# raiko
raiko-lib = { workspace = true }

# alloy
alloy-rlp = { workspace = true }
alloy-rlp-derive = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-provider = { workspace = true }
alloy-transport-http = { workspace = true }
alloy-consensus = { workspace = true }
alloy-network = { workspace = true }
alloy-rpc-client = { workspace = true }

# misc
anyhow = { workspace = true }
bincode = { workspace = true }
bytemuck = { workspace = true }
clap = { workspace = true }
structopt = { workspace = true }
flate2 = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
env_logger = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
tower = { workspace = true }
prometheus = { workspace = true }
lazy_static = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
reqwest_alloy = { workspace = true }
sha2 = { workspace = true }
proptest = { workspace = true }
rlp = { workspace = true }
url = { workspace = true }
cfg-if = { workspace = true }
cap = { workspace = true }
dirs = { workspace = true }

file-lock = "2.1.11"


[dev-dependencies]
assert_cmd = { workspace = true }
rstest = { workspace = true }
ethers-core = { workspace = true }

[features]
sgx = []
