// OpenVM ELF binaries for batch and aggregation proving
// These are generated by the openvm-builder during the build process

#[cfg(feature = "enable")]
pub const OPENVM_BATCH_ELF: &[u8] = include_bytes!("openvm-batch");

#[cfg(feature = "enable")]
pub const OPENVM_AGGREGATION_ELF: &[u8] = include_bytes!("openvm-aggregation");

#[cfg(not(feature = "enable"))]
pub const OPENVM_BATCH_ELF: &[u8] = &[];

#[cfg(not(feature = "enable"))]
pub const OPENVM_AGGREGATION_ELF: &[u8] = &[];
