[package]
name = "raiko-host"
version = "0.1.0"
edition = "2021"
default-run = "raiko-host"

[dependencies]

# provers
sp1-driver = { path = "../provers/sp1/driver", optional = true }
risc0-driver = { path = "../provers/risc0/driver", optional = true }
sgx-prover = { path = "../provers/sgx/prover", optional = true }

# raiko
raiko-lib = { workspace = true }
raiko-primitives = { workspace = true, features = ["c-kzg"] }
raiko-core = { workspace = true }

# alloy
alloy-rlp = { workspace = true }
alloy-rlp-derive = { workspace = true }
alloy-sol-types = { workspace = true }
alloy-primitives = { workspace = true }
alloy-rpc-types = { workspace = true }
alloy-provider = { workspace = true }
alloy-transport-http = { workspace = true }
alloy-consensus = { workspace = true }
alloy-network = { workspace = true }
alloy-rpc-client = { workspace = true }

# server
axum = { workspace = true }
tower-http = { workspace = true }
tower = { workspace = true }
utoipa-swagger-ui = { workspace = true }
utoipa-scalar = { workspace = true }
utoipa = { workspace = true }

# misc
anyhow = { workspace = true }
bincode = { workspace = true }
bytemuck = { workspace = true }
clap = { workspace = true }
flate2 = { workspace = true }
revm = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
hyper = { workspace = true }
env_logger = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
lru_time_cache = { workspace = true }
prometheus = { workspace = true }
lazy_static = { workspace = true }
once_cell = { workspace = true }
thiserror = { workspace = true }
reqwest = { workspace = true }
reqwest_alloy = { workspace = true }
sha2 = { workspace = true }
proptest = { workspace = true }
c-kzg = { workspace = true }
rlp = { workspace = true }
url = { workspace = true }
cfg-if = { workspace = true }
cap = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
rstest = { workspace = true }
ethers-core = { workspace = true }

[features]
# powdr = ["dep:powdr"]
sp1 = ["raiko-core/sp1"]
risc0 = ["raiko-core/risc0"]
sgx = ["raiko-core/sgx"]

[[bin]]
name = "raiko-host"
path = "src/bin/main.rs"

[[bin]]
name = "docs"
path = "src/bin/docs.rs"
