[package]
name = "risc0-guest"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "0.20.1" }

[package.metadata.risc0]
methods = ["guest"]

# cargo build
[features]
risc0 = []