services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - './monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus_storage:/prometheus'
    ports:
      - "9090:9090"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - 'grafana_storage:/var/lib/grafana'
volumes:
  grafana_storage: {}
  prometheus_storage: {}
