// Generated by risc0-builder with `cargo run --bin risc0-builder --features test`
// Placeholder: re-exports from boundless_batch until builder runs and overwrites with test binary
pub use super::boundless_batch::{
    BOUNDLESS_BATCH_ELF as TEST_BOUNDLESS_BATCH_ELF, BOUNDLESS_BATCH_ID as TEST_BOUNDLESS_BATCH_ID,
};
