[package]
name = "zisk-driver"
version = "0.1.0"
edition = "2021"

[features]
enable = []

[dependencies]
raiko-lib = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true }
tracing = { workspace = true }
reth-primitives = { workspace = true }
alloy-primitives = { workspace = true }
tokio = { workspace = true }
hex = { workspace = true }
bincode = { workspace = true }