[package]
name = "zisk-guest"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "zisk-batch"
path = "src/batch.rs"

[[bin]]
name = "zisk-aggregation"
path = "src/aggregation.rs"

[dependencies]
# Core Zisk dependencies
ziskos = { git = "https://github.com/0xPolygonHermez/zisk.git" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
bincode = { version = "1.3", default-features = false }

# Minimal dependencies for basic types - no heavy crypto libraries
# These should compile for RISC-V without issues
hex = { version = "0.4", default-features = false, features = ["alloc"] }