name: CI - All Provers

on:
  workflow_call:
  push:
    branches: ["main"]
    paths:
      - "pipelines/**"
      - "harness/**"
  pull_request:
    paths:
      - "pipelines/**"
      - "harness/**"
env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-test-native:
    uses: ./.github/workflows/ci-native.yml

  build-test-risc0:
    uses: ./.github/workflows/ci-risc0.yml

  build-test-sp1:
    uses: ./.github/workflows/ci-sp1.yml

  build-test-sgx-all:
    uses: ./.github/workflows/ci-sgx-all.yml
