name: Typo Check

on: [pull_request]

jobs:
  check-for-typos:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: [taiko-runner]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Check for typos
        uses: crate-ci/typos@master
