[package]
name = "raiko-metrics"
version = "0.1.0"
authors = ["Taiko Labs"]
edition = "2021"

[dependencies]
raiko-lib = { workspace = true }
prometheus = { workspace = true }
lazy_static = { workspace = true }
